name: Export and Import solutions

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "Name of the solution to work on from Power Platform"
        required: true

env:
  ENVIRONMENT_URL: ${{ secrets.SOURCE_ENVIRONMENT_URL }}
  CLIENT_ID: ${{ secrets.POWERPLATFORM_CLIENT_ID }}
  TENANT_ID: ${{ secrets.POWERPLATFORM_TENANT_ID }}
  SECRET_ID: ${{ secrets.POWERPLATFORM_SECRET_ID }}
  TARGET_ENVIRONMENT_URL: ${{ secrets.TARGET_ENVIRONMENT_URL }}

permissions:
  contents: write

jobs:
  export-from-powerapps:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: who-am-i action
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ env.ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ env.SECRET_ID }}
          tenant-id: ${{ env.TENANT_ID }}

      - name: export-solution action
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ env.ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ env.SECRET_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          solution-name: ${{ github.event.inputs.solution_name }}
          solution-output-file: ./${{ github.event.inputs.solution_name }}.zip

      - name: Upload Exported Solution
        uses: actions/upload-artifact@v2
        with:
          name: exported-solution
          path: ./${{ github.event.inputs.solution_name }}.zip

  import-powerapps:
    runs-on: ubuntu-latest
    needs: export-from-powerapps

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download Exported Solution
        uses: actions/download-artifact@v2
        with:
          name: exported-solution
          path: ./

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: who-am-i action
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ env.TARGET_ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ env.SECRET_ID }}
          tenant-id: ${{ env.TENANT_ID }}

      - name: Import PowerApps Solution
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ env.TARGET_ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ env.SECRET_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          solution-file: ./${{ github.event.inputs.solution_name }}.zip
          run-asynchronously: true
  check-solution:
    runs-on: ubuntu-latest
    needs: import-powerapps

    steps:
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: check-solution-status action
        uses: microsoft/powerplatform-actions/check-solution@v1
        with:
          environment-url: ${{ env.TARGET_ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ env.SECRET_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          path: ./${{ github.event.inputs.solution_name }}.zip
